os:
  - linux
  - osx

language: java

jdk:
  - openjdk8

script:
  - ./gradlew clean build

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  dry-run: false
  on:
    branch: master