matrix:
  include:
  - os: linux
    language: java
    jdk: oraclejdk8
    script:
    - ./gradlew clean build
    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/
      - $HOME/.konan/cache/
      - $HOME/.konan/dependencies/
    deploy:
      provider: script
      script: ./gradlew publish
      skip_cleanup: true
      dry-run: false
      on:
        branch: master
#  - os: windows
#    language: shell
#    env:
#    - JAVA_HOME=c:\\java8
#    script:
#    - ./travis_windows_setup.bat
#    - ./gradlew.bat clean windowsTest
#    before_cache:
#    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
#    cache:
#      directories:
#      - $HOME/.gradle/caches/
#      - $HOME/.gradle/wrapper/
#      - $HOME/.konan/cache/
#      - $HOME/.konan/dependencies/
#    deploy:
#      provider: script
#      script: ./gradlew.bat publishWindowsPublicationToMavenRepository
#      skip_cleanup: true
#      dry-run: false
#      on:
#        branch: master
  - os: osx
    language: java
    jdk: oraclejdk8
    script:
    - ./gradlew clean macosTest
    before_cache:
      - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
      - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/.konan/cache/
        - $HOME/.konan/dependencies/
    deploy:
      provider: script
      script: ./gradlew publishMacosPublicationToMavenRepository
      skip_cleanup: true
      dry-run: false
      on:
        branch: master
