os:
  - linux
  - osx

language: java

jdk:
  - openjdk8

script:
  - ./gradlew clean build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.konan/cache/
    - $HOME/.konan/dependencies/

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  dry-run: false
  on:
    branch: master